package metriceventstream

import (
	"github.com/cep21/circuit/v3/metriceventstream"
)

// generated by goforward github.com/cep21/circuit/v3/metriceventstream github.com/cep21/circuit/metriceventstream

// MetricEventStream is a HTTP handler that supports hystrix's metric stream API
// See https://github.com/Netflix/Hystrix/wiki/Metrics-and-Monitoring#metrics-event-stream.  It requires that your
// metrics are monitored by rolling stats, because it uses them to get health information.
type MetricEventStream = metriceventstream.MetricEventStream
